const list = [
	"You can actually zoom in older versions.",
	"Also check out Groove Launcher!",
	"Also check out Cookie Clicker!",
	"Metro Notes",
	"November 19, 2003",
	"October 21, 2010",
	"October 29, 2012",
	"Come to Brazil",
	"transform: translateX(500px);",
	"notesDiv.classList.add('to');",
	"Special thanks to my cats",
	"Merto Noets",
	"Error",
	"Create your note today!",
	"Except in Nebraska",
	"Order today!",
	"It's $99!",
	"Start Metro Notes.",
	"Groove Launcher incident 1934",
	"There is actually no limit to these messages. The cat(Felis catus), also referred to as the domestic cat, is a small domesticated carnivorous mammal. It is the only domesticated species of the family Felidae. Advances in archaeology and genetics have shown that the domestication of the cat occurred in the Near East around 7500 BC.",
	"Add emojis to your notes 🤑",
	"This was written 21:17 BRT with 23% battery",
	"Pocket edition!",
	"Webview based!",
	"Many, many notes were harmed during the making of this app.",
	"Do not press the f6 key while making a note.",
	"Don't believe the last message.",
	"11 missed calls from Metro Notes",
	"𝓜𝓮𝓽𝓻𝓸 𝓝𝓸𝓽𝓮𝓼",
	"Essa men- Sorry!",
	"This message has a x2 chance of appearing by the way.",
	"This message has a x2 chance of appearing by the way.",
	"Insert text here",
	"Star my project on github!",
	"That's it, that's the message.",
	"My clipboard is full of webcode.",
	"Also check out Metro Notes! Wait a minute...",
	"Do you like this message?",
	"Don't worry about it.",
	"I'll rate your note 5 stars.",
	"Each message has a 1,075% chance of appearing (except one)",
	"6 MONTHS?",
	"Ok.",
	"Okay.",
	"The github logo in the button is actually over the button border. ",
	"Not sponsored by Groove Launcher!",
	"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">",
	"This app was fully made in a phone.",
	"So Metro...",
	"Write your note today!",
	"Note not found!",
	"This message is ai generated.",
	"Happy birthday someone!",
	"Special thanks to CorruptionVR",
	"Do not try the alpha release.",
	"WebView rendered!",
	"Supports Android Lollipop!",
	"Targets Android Red Valvet Cake!",
	"Supports Groove Launcher!",
	"Maybe",
	"Do a barrel roll!",
	"#metronotes",
	"Unlock premium to see this message.",
	"Do they even care?",
	"Where is my speech bubble!?",
	"I'm actually offscreen.",
	"I'm not just a message by the way.",
	"app-metro-notes",
	"Italic text!",
	"Works better with Groove Launcher.",
	"Developed with WebCode and ACode",
	"Quill!",
	"Drag and drop images to your note!",
	"This message was added in version b0.3.0",
	"cubic-bezier(1,0,0,1);",
	"@ghplayer2000",
	"Also check out MetroOS!",
	"[✓] Add messages",
	"§l Metro Notes",
	"☆ Metro Notes ☆",
	"《 This way",
	"Metro + Notes = Metro Notes",
	"?deppilf txet ym si yhW",
	"ǝuoqɹǝuuᴉp",
	"¿uʍop ǝpᴉsdn ʇxǝʇ ʎɯ sᴉ ʎɥW",
	"Ş̷̡̛̛̹̺̪̝͈̫̈́̈͌́͂̌͜͞͠ͅu̧̞̣̻̙͑̉̏͛͘͢͜ͅp̟̖̣̩͇̔̀̇̃͋̚ȩ̧̢̦̦͕͒̋̇̈͞ṟ̟̞͉͙̝̗̘̝̊͊̂͑̄̽ Ş̻͖̠̖̿̒͋́͗̌̔͐̕c̡̢͉̤͔͚̳̀͐͗̂̾́̊̄ą̦͖͎͈̣̳̀̓͊̀̽̐̊͌͠͝r̛̮͓̬͕͚͗̑̈́̾̚y̵͉̟͖̜̘̾̔̅͗́̎͐̍̍͘͜ͅ Ţ̨̞͚̖͗̋̋́̏͟ȩ̴̢̲̘̱̩̎͋̍̂̎̀̈́̚x̴̥͓̼̝̱̣͚̋̒͗͝͠t̷͔̘̘̗̰͂͊̎́̆̐",
	"Nice."
];


function mes() {
	const rand = Math.floor(Math.random() * list.length);
	const randword = list[rand];
	document.getElementById("mes").textContent = randword;
}

mes();

const theme = localStorage.getItem('theme');
if (theme === 'dark') {
	document.body.classList.add('darktheme');
	document.getElementById('appbar').classList.add('dthemeabar');
	document.getElementById('github').classList.add('dthemeabutton');
}