name: Compile Android

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew

    - name: Build with Gradle
      working-directory: ./android
      run: ./gradlew build

    - name: Copy web content to Android assets
      run: |
        mkdir -p ./android/app/src/main/assets/web_content
        shopt -s extglob
        cp -r !(android) ./android/app/src/main/assets/web_content/
